### ISSUE TITLE
Currently not working?

### ISSUE THREAD

**Issue by momspaghetti123** [MayouKurayami/KK_CrossFader#2]
Since I got the plugin a few months ago, it never worked? I always get the stutter between transitions, and it just gets stuck before switching.

Is that a possible compatibility issue?

**Comment by MayouKurayami** [comment]
I'm not exactly sure what you're describing.
Stutter **_between_** transitions? Which means all the time?
And what does getting "stuck" mean? The game freezes completely beyond recovery?

Also, in case you didn't know, this plugin only affects transitions between different motions (animations) of the **same** position, such as the transition between idle, weak motion, and strong motion.
It does not help with switching from one position or mode to another.

**Comment by momspaghetti123** [comment]
Looks like I was just stupid. Everything works great now! Appreciate the response.
